### ISSUE TITLE
Locale always stopped on reboot

### ISSUE THREAD

**Issue by dfnyc** [droboports/locale#1] opened 2015-10-04 15:03 UTC
Hi - Since re-installing locale after upgrading to Firmware 3.3.0, locale no longer automatically starts on reboot. I have to manually go into Dashboard and start the service. Any idea why that would be? It creates difficulty installing apps that depend on locale (e.g. crashplan) since the service isn't found on reboot and the installer fails...

**Comment by ricardopadilha** [comment] 2015-10-05 14:01
This means you probably have duplicate entries on your `.servicerc` file. The easiest way to fix this is to mount the `DroboApps` share, and delete the file `.servicerc`. This file is hidden, so make sure your computer is setup to show hidden files.

**Comment by ricardopadilha** [comment] 2015-10-05 14:02
If you manage to see the `.servicerc` file, please check its content to see if there is a duplicated line `locale_enabled="YES"`.

**Comment by dfnyc** [comment] 2015-10-06 03:34
I was able to take a look at .servicerc. There was not a duplicate line in there, but it did show locale_enable="no". Another odd thing was that unlike all the other files in DroboApps which are owned by root, it was showing that .servicerc was owned by my Drobo Admin ID which I use to ssh to the drobo.

I deleted .servicerc and rebooted. When it came back, at least now .servicerc was owned by root (not sure how important that is), but it still did not have duplicate entries and still showed locale_enable="no". If I go into Dashboard and click start for locale, .servicerc is then updated to show locale_enable="yes", but when I reboot it goes back to locale_enable="no" (again with no duplicates).

I can also share the contents of my /tmp/DroboApps/log.txt file if that would be useful, but let me know the best way to get that to you since it's too large to attach here.

Please let me know if there is anything else I should try.

**Comment by ricardopadilha** [comment] 2015-10-06 03:38
Try to upload it to pastebin.com.

**Comment by dfnyc** [comment] 2015-10-06 03:43
Thanks for the help. It's here: http://pastebin.com/x33uThNy

**Comment by ricardopadilha** [comment] 2015-10-06 04:20
From the pastebin I can see that locale is booting up as disabled, but it is being configured as enabled later on. So there is something wrong with the shutdown that is disabling it.

Could you please ask for a reboot while you have an ssh window running the command `tail -f /tmp/DroboApps/log.txt`, and then post the content of that window? I need to see what is happening at shutdown to find out why is locale being disabled.

**Comment by dfnyc** [comment] 2015-10-06 04:33
Here it is. Looks like there's an awk error during shutdown...

$ tail -f /tmp/DroboApps/log.txt 
- /bin/grep -q stopped
- echo locale is enabled and running
- /bin/grep -q running
- echo locale is enabled and running
- /bin/grep .\* is .\* and .*
- _status=locale is enabled and running
- echo locale is enabled and running
- _result=0
- [ 0 -eq 1 ]
- exit 0
- date +%Y-%m-%d %H-%M-%S
- echo 2015-10-05 21-30-51: /usr/bin/DroboApps.sh stop
- _echo_end=1
- _operation=stop
- shift
- stop_apps
- local _apps=
- local _app=
- local _enabled=0
- _list_droboapps
- /usr/bin/find /mnt/DroboFS/Shares/DroboApps ( ! -regex ._/.._ ) -mindepth 1 -maxdepth 1 -type d -exec /usr/bin/basename {} ;
- _apps=locale
  apache
  java8
  Network Trash Folder
  Temporary Items
  perl
  crashplan
  plex
  sudo
  openssh
  python2
- [ -n locale
  apache
  java8
  Network Trash Folder
  Temporary Items
  perl
  crashplan
  plex
  sudo
  openssh
  python2 ]
- _is_enabled locale
- local _value=
- [ ! -f /mnt/DroboFS/Shares/DroboApps/.servicerc ]
- /usr/bin/awk -F = -v name=locale_enable $1 == name { gsub(/"/, "", $2); print $2 } /mnt/DroboFS/Shares/DroboApps/.servicerc
- _value=YES
- [ -z YES ]
- return 0
- _enabled=1
- stop_app locale
- local _appName
- local _appDir
- _appDir=/mnt/DroboFS/Shares/DroboApps/locale
- [ ! -d /mnt/DroboFS/Shares/DroboApps/locale ]
- [ ! -f /mnt/DroboFS/Shares/DroboApps/locale/service.sh ]
- echo Stopping locale.
- cd /mnt/DroboFS/Shares/DroboApps/locale
- /bin/sh /mnt/DroboFS/Shares/DroboApps/locale/service.sh stop
- echo locale successfully stopped.
- /usr/bin/DroboAppsAnalytics.sh -e stop -n locale
- _poststop_app locale
- _set_enabled locale NO
- local _value=
- [ ! -f /mnt/DroboFS/Shares/DroboApps/.servicerc ]
- /usr/bin/awk -F = -v name=locale_enable $1 == name { gsub(/"/, "", $2); print $2 } /mnt/DroboFS/Shares/DroboApps/.servicerc
  awk: cmd. line:1: Input/output error
- _value=
- [ -z  ]
  /usr/bin/DroboApps.sh: line 1: can't create /mnt/DroboFS/Shares/DroboApps/.servicerc: Read-only file system
- echo locale_enable="NO"
- return 0
- [ 1 -eq 1 ]
- _set_enabled locale YES
- local _value=
- [ ! -f /mnt/DroboFS/Shares/DroboApps/.servicerc ]
- /usr/bin/awk -F = -v name=locale_enable $1 == name { gsub(/"/, "", $2); print $2 } /mnt/DroboFS/Shares/DroboApps/.servicerc
  awk: cmd. line:1: Input/output error
- _value=
  Connection to 192.168.1.190 closed by remote host.

**Comment by ricardopadilha** [comment] 2015-10-06 04:40
This is the problem:

```
/usr/bin/DroboApps.sh: line 1: can't create /mnt/DroboFS/Shares/DroboApps/.servicerc: Read-only file system
```

Apparently the system is already read-only due to shutdown when `locale/service.sh stop` is called. All of this is happening inside the SDK. There is nothing that I can do, sorry.

Do you happen to have DroboCare? This would be a perfect situation to create a support ticket.

**Comment by dfnyc** [comment] 2015-10-06 04:48
OK, thanks. I don't have DroboCare, but I'll see if I can get any help from their support. Any idea why this would be effecting my Drobo (and I guess not other people since I haven't seen this issue reported by others)? It seems like this issue started after updating the Firmware to 3.3.0, so maybe the issue is there?

**Comment by ricardopadilha** [comment] 2015-10-06 05:36
To be honest I'm not entirely sure why this is only happening to you. As far as I can tell the problem is that when you shutdown the Drobo, the shutdown procedure is not waiting for the DroboApps to shutdown themselves. This could be something with 3.3.0, but it could just as well be an older issue.

**Comment by dfnyc** [comment] 2015-10-06 14:29
OK, thanks for the help. I'll post back if I find any info that might be helpful to others...

**Comment by ricardopadilha** [comment] 2015-10-06 18:57
I'll close this issue since this is not a problem of the locale DroboApp.

**Closed as completed by ricardopadilha** 2015-10-06 18:57 UTC

**Comment by 4bitfocus** [comment] 2015-10-31 04:00
I'm seeing the same issue. Did you figure anything out, @dfnyc ?
